###
POST http://localhost:3002/api/persons/ 
content-type: application/json

{
    "name":"joseph",
    "number": "321335245"
}


###
POST http://localhost:3002/api/persons/ 
content-type: application/json

{
    "name":"Alberto",
    "number": "123-456-898"
}