POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "georgeeee",
    "password" : "1234",
    "username": "JimiTheMan"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "georgios1",
    "password" : "1234",
    "username": "georgios1"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "Maria",
    "password" : "1234",
    "username": "Maria"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "Leo",
    "password" : "Leo",
    "username": "Leo"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "Sofia",
    "password" : "Sofia",
    "username": "Sofia123"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "Takis",
    "password" : "Takis",
    "username": "Takis1"
}