POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "georgeeee",
    "password" : "1234",
    "username": "JimiTheMan"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "Georgios",
    "password" : "1234567",
    "username": "GoergieBoy"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "Maria",
    "password" : "1234",
    "username": "Maria"
}

###
POST http://localhost:3003/api/users/
Content-Type : application/json

{
    "name": "Leo",
    "password" : "Leo",
    "username": "Leo"
}