# fly.toml app configuration file generated for phonebook-backend-george on 2025-04-24T12:44:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-george'
primary_region = 'fra'

[build]

[env]
  PORT = "3002"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
