POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2ODE5ZDYyOTQ1YzU3ODIyYjFjNWYyZmYiLCJpYXQiOjE3NDY1MjM2OTR9.igY2TgGG8ph29tXPFFiIMmKtqMXRkqMBpoi28EHIfnk

{
  "title": "The Shape of water",
  "author": "Maria",
  "url": "https://crodur.com",
  "likes": 15
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2ODE5ZDYyOTQ1YzU3ODIyYjFjNWYyZmYiLCJpYXQiOjE3NDY1MjM2OTR9.igY2TgGG8ph29tXPFFiIMmKtqMXRkqMBpoi28EHIfnk

{
  "title": "Onwards to the death",
  "author": "Maria",
  "url": "https://crodur.com",
  "likes": 33
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2ODE5ZWIyMWIyMjNlNWRjZTE4MjQ0YjEiLCJpYXQiOjE3NDY1MjkwNjR9.YCHF-0egEuH5G0fxk9qiTzWPEYI6pXfiiCJo_d8Mdzk

{
  "title": "The Shape of water",
  "author": "Maria",
  "url": "https://crodur.com",
  "likes": 15
}


# post for george 

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdvZXJnaWVCb3kiLCJpZCI6IjY4MTlmMDY5MWNiZWYyNjQ5MTZjNzRmZCIsImlhdCI6MTc0NjUzMDQxOH0.RRLQrUdNTokszXpaHrlA0xNEpTI92VPqEaXZrPibVWc

{
  "title": "The adventures of Geroge",
  "author": "George",
  "url": "https://crodurfrrr.com",
  "likes": 1444
}
