POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2ODE5ZDYyOTQ1YzU3ODIyYjFjNWYyZmYiLCJpYXQiOjE3NDY1MjM2OTR9.igY2TgGG8ph29tXPFFiIMmKtqMXRkqMBpoi28EHIfnk

{
  "title": "The Shape of water",
  "author": "Maria",
  "url": "https://crodur.com",
  "likes": 15
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2ODE5ZDYyOTQ1YzU3ODIyYjFjNWYyZmYiLCJpYXQiOjE3NDY1MjM2OTR9.igY2TgGG8ph29tXPFFiIMmKtqMXRkqMBpoi28EHIfnk

{
  "title": "Onwards to the death",
  "author": "Maria",
  "url": "https://crodur.com",
  "likes": 33
}

