POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Crodur",
  "author": "unknown",
  "url": "https://crodur.com",
  "likes": 15
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "typepad",
  "author": "Elise Blaha",
  "url": "https://eliseblaha.typepad.com/",
  "likes": 18
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
 
  "author": "Elise Blaha",
  "url": "https://flaviocopes.com/",
  "likes": 199,
  "title":"Somewhere over the rainbow"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdvZXJnaWVCb3kiLCJpZCI6IjY4MTkxNmNlYWFlZjRlNjhhYWQ4NzUyMSIsImlhdCI6MTc0NjQ3NzU3MH0.5GHu-aMGoV2ll7_Y73XdHlaAxmC5HN2wC9WOuBOj5B4

{
 
  "author": "Elliot",
  "url": "https://google.com/",
  "likes": 190000,
  "title":"The web in your hands"
}


###
POST http://localhost:3003/api/blogs
Content-Type : application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2ODE5MmRjYjQ1ZDJkMGZlZGQ4YjMxNTYiLCJpYXQiOjE3NDY0ODA2MDF9.lt4Gv63qULn0cWQ4GqCb8d5ifXkAVfCxbUJiv7TzrZo

{
  "author":"Maria",
  "url":"https://google.com",
  "likes":123,
  "title":"Explore the digital word"}

###
POST http://localhost:3003/api/blogs
Content-Type : application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2ODE5MmRjYjQ1ZDJkMGZlZGQ4YjMxNTYiLCJpYXQiOjE3NDY0ODA2MDF9.lt4Gv63qULn0cWQ4GqCb8d5ifXkAVfCxbUJiv7TzrZo

{
  "author":"Maria",
  "url":"https://google123.com",
  "likes":123,
  "title":"March ahead!"}