POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Crodur",
  "author": "unknown",
  "url": "https://crodur.com",
  "likes": 15
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "typepad",
  "author": "Elise Blaha",
  "url": "https://eliseblaha.typepad.com/",
  "likes": 18
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "flavio",
  "author": "Flavio Copes",
  "url": "https://flaviocopes.com/",
  "likes": 199
}